replicaCount: 1

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: syseleven/designate-certmanager-webhook
  tag: 0.2.1
  pullPolicy: IfNotPresent

# Designate secret name. If you fill in the openstack settings below the chart will create and fill your secret. If not please consult the README for instructions on how to create your own secret.
# credentialsSecret: cloud-credentials

openstack:
  # Openstack credentials and cloud settings. You must fill in all blank fields or create you own secret.
  username: ""
  password: ""
  project_id: ""
  region_name: ""
  auth_url: ""
  domain_name: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
