replicaCount: 1

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: syseleven/designate-certmanager-webhook
  tag: 0.2.1
  pullPolicy: IfNotPresent

# Designate secret name
credentialsSecret: cloud-credentials

openstack:
  # Openstack credentials and cloud settings
  username:
  password:
  project_id:
  region_name:
  auth_url:
  domain_name:

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
