name: Deploy Worklow

on:
  push:
    tags:
      - '*'
  # test!
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Push
      run: make build ci-push
